<?php

namespace Tests\Unit;

use App\Data\Validators\DateValidator;
use App\Data\Validators\Exceptions\InvalidDateException;
use PHPUnit\Framework\TestCase;

class DateValidatorTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A Date is valid.
     *
     * @return void
     */
    public function testValidDateTest()
    {
        $validator = DateValidator::validateDate('1967/05/09 13:25');
        $this->assertTrue($validator);

        $validator = DateValidator::validateDate('1967/05/09');
        $this->assertTrue($validator);
    }

    /**
     * A Date is invalid.
     *
     * @return void
     */
    public function testInvalidDateTest()
    {
        $this->expectException(InvalidDateException::class);
        $valid = DateValidator::validateDate('1967-05-09');
        $this->assertFalse($valid);

        $this->expectException(InvalidDateException::class);
        $valid = DateValidator::validateDate('1967-05-09 13:25');
        $this->assertFalse($valid);
    }

    /**
     * A Date is invalid.
     *
     * @return void
     */
    public function testEmptyDateTest()
    {
        $this->expectException(InvalidDateException::class);
        $valid = DateValidator::validateDate('');
        $this->assertFalse($valid);
    }
}
