<?php

namespace Tests\Unit;

use Josantonius\Session\Session;
use PHPUnit\Framework\TestCase;
use App\Data\SessionManager;

class SessionTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $dateArray = [
            'Currentdate' => '2019/11/25 07:45',
            'Birthdate' => '1967/05/09',
            'Years' => '52',
            'Days' => '18996',
            'Hours' => '460639',
        ];

        $sessionManager = new SessionManager();
        $sessionManager->addDate($dateArray);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testSessionManagerTest()
    {
        // Get date from session
        $dates = Session::get('dates');
        $this->assertIsArray($dates);
        $this->assertIsArray($dates[0]);

        $date = $dates[0];
        $this->assertSame('52', $date['Years']);
        $this->assertSame('18996', $date['Days']);
        $this->assertSame('460639', $date['Hours']);
    }
}
