<?php

namespace Tests\Unit;

use App\Data\DateValidator;
use PHPUnit\Framework\TestCase;

class ValidatorTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A Date is valid.
     *
     * @return void
     */
    public function testValidTest()
    {
        $validator = DateValidator::validateDate('1967/05/09 13:25');
        $this->assertTrue($validator);

        $validator = DateValidator::validateDate('1967/05/09');
        $this->assertTrue($validator);
    }

    /**
     * A Date is invalid.
     *
     * @return void
     */
    public function testInalidTest()
    {
        $validator = DateValidator::validateDate('1967-05-09');
        $this->assertFalse($validator);

        $validator = DateValidator::validateDate('1967-05-09 13:25');
        $this->assertFalse($validator);
    }
}
